spring:
  application:
    name: istudy-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.67.2:8848
    #sentinel:
      #transport:
        #port: 8721
        #dashboard: 124.70.67.2:8080
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: istudy-note
        url: lb://istudy-note
        predicates:
          - Path=/api/note/**
        filters:
          - # 前缀过滤，默认配置下，我们的请求路径是 http://localhost:9000/istudy-note/** 这时会路由到指定的服务
          # 此处配置去掉 1 个路径前缀，再配置上面的 Path=/api/**，就能按照 http://localhost:9000/api/** 的方式访问了
          - StripPrefix=1
      - id: istudy-room
        url: lb://istudy-room
        predicates:
          - Path=/api/room
        filters:
          - StripPrefix=1
      - id: istudy-user
          url: lb://istudy-user
          predicates:
            - Path=/api/user
          filters:
            - StripPrefix=1
      - id: istudy-reservation
          url: lb://istudy-reservation
          predicates:
            - Path=/api/reservation
          filters:
            - StripPrefix=1
server:
  port: 9000

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: debug